---
# tasks file for osquery agent for linux

- name: osquery-agent-linux | copy GPG key to remote
  copy:
    src: osquery.gpg
    dest: /tmp/osquery.gpg
  become: yes
  tags:
    - install

- name: osquery-agent-linux | download osquery agent deb if debian
  ansible.builtin.get_url:
    url: https://pkg.osquery.io/deb/osquery_5.12.1-1.linux_amd64.deb
    dest: /tmp/osquery_5.12.1-1.linux_amd64.deb
    checksum: sha256:051c287741d71b09184cb6bc53065cda972e3c27592b1e558696aaec9f0eb013

