---
# tasks file for osquery agent for linux
tasks:
  - name: Install, configure, and start osquery agent on Linux
    block:
      - name: osquery-agent-linux | download osquery agent deb if debian
        ansible.builtin.get_url:
          url: https://pkg.osquery.io/deb/osquery_5.12.1-1.linux_amd64.deb
          dest: /tmp/osquery_5.12.1-1.linux_amd64.deb
          checksum: sha256:051c287741d71b09184cb6bc53065cda972e3c27592b1e558696aaec9f0eb013

      - name: osquery-agent-linux | install osquery agent deb if debian
        ansible.builtin.apt:
          deb: /tmp/osquery_5.12.1-1.linux_amd64.deb
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    become: yes
    tags:
      - install

    block:
      - name: osquery-agent-linux | download osquery agent rpm if RHEL
        ansible.builtin.get_url:
          url: https://pkg.osquery.io/rpm/osquery-5.12.1-1.linux.x86_64.rpm
          dest: /tmp/osquery-5.12.1-1.linux.x86_64.rpm
          checksum: eb3dccd38dec8f92bfd8616fd24f1210486f5f02ffc9d6c016827ab668f67c08
    when: ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'CentOS'
    become: yes
    tags:
      - install

#- name: osquery-agent-linux | copy GPG key to remote
#  copy:
#    src: osquery.gpg
#    dest: /tmp/osquery.gpg
#  become: yes
#  tags:
#    - install

